using System;
using System.Collections.Generic;
using AutomataLibrary;

namespace AutomataGeneratorLibrary
{
    /// <summary>
    /// Abstract class of automata generator.
    /// </summary>
    public abstract class AbstractAutomataGenerator
    {
        /// <summary>
        /// Nondeterministic finite automaton generated by constructor <see cref="AbstractAutomataGenerator()"/>.
        /// </summary>
        protected NFA NFA;

        /// <summary>
        /// Set of all symbols contained in generated automaton <see cref="NFA"/>.
        /// </summary>
        protected SortedSet<char> MAlphabet;

        /// <summary>
        /// Set of states of generated automaton <see cref="NFA"/>.
        /// </summary>
        protected SortedSet<int> MStates;

        /// <summary>
        /// Initial state of generated automaton <see cref="NFA"/>.
        /// </summary>
        protected int MInitialState;

        /// <summary>
        /// Set of final states of generated automaton <see cref="NFA"/>.
        /// </summary>
        protected SortedSet<int> MFinalStates;

        /// <summary>
        /// List of delta transitions of generated automaton <see cref="NFA"/>.
        /// </summary>
        protected List<Tuple<int, string, int>> DeltaItems;

        /// <summary>
        /// List of epsilon transition of generated automaton <see cref="NFA"/>.
        /// </summary>
        protected List<Tuple<int, int>> EpsilonItems;

        /// <summary>
        /// Initializes a new instance of the <see cref="AbstractAutomataGenerator"/>.
        /// </summary>
        protected AbstractAutomataGenerator()
        {
            MAlphabet = new SortedSet<char>();
            MStates = new SortedSet<int>();
            DeltaItems = new List<Tuple<int, string, int>>();
            EpsilonItems = new List<Tuple<int, int>>();
            MFinalStates = new SortedSet<int>();
        }

        /// <summary>
        /// Returns generated automaton <see cref="NFA"/>.
        /// </summary>
        /// <returns>Generated automaton <see cref="NFA"/>.</returns>
        public NFA GetAutomata()
        {
            return NFA;
        }
    }
}
